services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    ports:
      - "3000:5000"
    depends_on:
      - backend

  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile    
    ports:
      - "8000:8000"  
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload